In [1]:
# from vnstock import Vnstock
# import pandas as pd
# import time

# symbols = [
#     "ACB","BCM","BID","BVH","CTG","FPT","GAS","GVR","HDB","HPG",
#     "MBB","MSN","MWG","PLX","POW","SAB","SSI","STB","TCB","TPB",
#     "VCB","VHM","VIB","VIC","VJC","VNM","VPB","VRE","VND","VIX",

#     "DXG","DIG","NLG","KDH","PDR","NVL","HDG","CEO","SCR","HDC",
#     "IDC","BCG","KBC","SZC","IJC","TIP","NTL","AGG","DRH","LDG",

#     "DGC","DCM","DPM","CSV","LAS","BFC","PLC","PGD","PET","PVT",
#     "PVS","PVD","BSR","OIL","GEX","GEE","PC1","TV2","REE","GEG",

#     "NT2","PPC","HND","QTP","TTA","POW","VSH","SJD","TMP","CHP",

#     "CMG","DGW","FRT","CTR","ELC","VGI","FOX","SGT","VTP","SCS",

#     "PNJ","DOJI","FMC","ANV","IDI","VHC","MPC","ACL","LTG","DBC",

#     "HCM","VCI","BSI","SHS","CTS","FTS","AGR","MBS","BVS","TVS"
# ]

# vn = Vnstock()
# all_data = []

# # Chỉ cần delay ngắn nếu dùng code xử lý lỗi bên dưới
# REQUEST_DELAY = 3.5

# for symbol in symbols:
#     print(f"🔄 Đang xử lý mã: {symbol}...")
    
#     # Khởi tạo object stock
#     stock = vn.stock(symbol=symbol, source="VCI")

#     for func, name in [
#         (stock.finance.income_statement, "income_statement"),
#         (stock.finance.balance_sheet, "balance_sheet"),
#         (stock.finance.cash_flow, "cash_flow"),
#     ]:
#         # Vòng lặp thử lại (Retry mechanism)
#         while True:
#             try:
#                 print(f"   -> Đang tải {name}...", end="")
#                 df = func(period="quarter")
                
#                 df["symbol"] = symbol
#                 df["report"] = name
#                 all_data.append(df)
#                 print(" ✅ Xong")
                
#                 # Ngủ ngắn sau khi thành công
#                 time.sleep(REQUEST_DELAY)
#                 break # Thoát vòng lặp while để sang báo cáo tiếp theo
                
#             except (Exception, SystemExit) as e:
#                 # Bắt cả lỗi thường và lỗi SystemExit do rate limit
#                 print(f"\n⚠️ Gặp lỗi hoặc bị chặn Rate Limit.")
#                 print("⏳ Đang tạm dừng 65 giây để hồi phục quota...")
#                 time.sleep(65) # Chờ 65s (hơn 1 phút) để reset limit
#                 print("▶️ Đang thử lại...")
#                 # Code sẽ tự quay lại đầu vòng while để gọi lại hàm func()

# # Xuất file CSV giữ nguyên số dài
# final_df = pd.concat(all_data, ignore_index=True)
# final_df.to_csv("raw_financial_data.csv", index=False, encoding='utf-8-sig', float_format='%.0f')

# print("\n🎉 Hoàn thành tất cả!")

In [2]:
# from vnstock import Vnstock
# import pandas as pd
# import time

# symbols = [
#     "ACB","BCM","BID","BVH","CTG","FPT","GAS","GVR","HDB","HPG",
#     "MBB","MSN","MWG","PLX","POW","SAB","SSI","STB","TCB","TPB",
#     "VCB","VHM","VIB","VIC","VJC","VNM","VPB","VRE","VND","VIX",

#     "DXG","DIG","NLG","KDH","PDR","NVL","HDG","CEO","SCR","HDC",
#     "IDC","BCG","KBC","SZC","IJC","TIP","NTL","AGG","DRH","LDG",

#     "DGC","DCM","DPM","CSV","LAS","BFC","PLC","PGD","PET","PVT",
#     "PVS","PVD","BSR","OIL","GEX","GEE","PC1","TV2","REE","GEG",

#     "NT2","PPC","HND","QTP","TTA","POW","VSH","SJD","TMP","CHP",

#     "CMG","DGW","FRT","CTR","ELC","VGI","FOX","SGT","VTP","SCS",

#     "PNJ","DOJI","FMC","ANV","IDI","VHC","MPC","ACL","LTG","DBC",

#     "HCM","VCI","BSI","SHS","CTS","FTS","AGR","MBS","BVS","TVS"
# ]

# vn = Vnstock()
# all_data = []

# REQUEST_DELAY = 3.5

# for symbol in symbols:
#     print(f"🔄 Đang xử lý mã: {symbol}...")

#     # Bắt lỗi symbol invalid
#     try:
#         stock = vn.stock(symbol=symbol, source="VCI")
#     except ValueError:
#         print(f"❌ Symbol không hợp lệ: {symbol} -> bỏ qua")
#         continue

#     for func, name in [
#         (stock.finance.income_statement, "income_statement"),
#         (stock.finance.balance_sheet, "balance_sheet"),
#         (stock.finance.cash_flow, "cash_flow"),
#     ]:

#         while True:
#             try:
#                 print(f"   -> Đang tải {name}...", end="")
#                 df = func(period="quarter")

#                 df["symbol"] = symbol
#                 df["report"] = name
#                 all_data.append(df)

#                 print(" ✅ Xong")
#                 time.sleep(REQUEST_DELAY)
#                 break

#             except (Exception, SystemExit):
#                 print(f"\n⚠️ Rate limit hoặc lỗi API")
#                 print("⏳ Chờ 65s rồi thử lại...")
#                 time.sleep(65)
#                 print("▶️ Thử lại...")

# final_df = pd.concat(all_data, ignore_index=True)
# final_df.to_csv(
#     "raw_financial_data.csv",
#     index=False,
#     encoding="utf-8-sig",
#     float_format="%.0f"
# )

# print("\n🎉 Hoàn thành tất cả!")

In [3]:
from vnstock import Vnstock
import pandas as pd
import time

symbols = [
    "ACB","BCM","BID","BVH","CTG","FPT","GAS","GVR","HDB","HPG",
    "MBB","MSN","MWG","PLX","POW","SAB","SSI","STB","TCB","TPB",
    "VCB","VHM","VIB","VIC","VJC","VNM","VPB","VRE","VND","VIX",

    "DXG","DIG","NLG","KDH","PDR","NVL","HDG","CEO","SCR","HDC",
    "IDC","BCG","KBC","SZC","IJC","TIP","NTL","AGG","DRH","LDG",

    "DGC","DCM","DPM","CSV","LAS","BFC","PLC","PGD","PET","PVT",
    "PVS","PVD","BSR","OIL","GEX","GEE","PC1","TV2","REE","GEG",

    "NT2","PPC","HND","QTP","TTA","POW","VSH","SJD","TMP","CHP",

    "CMG","DGW","FRT","CTR","ELC","VGI","FOX","SGT","VTP","SCS",

    "PNJ","DOJI","FMC","ANV","IDI","VHC","MPC","ACL","LTG","DBC",

    "HCM","VCI","BSI","SHS","CTS","FTS","AGR","MBS","BVS","TVS"
]

symbols = list(dict.fromkeys(symbols))

vn = Vnstock()
all_data = []

REQUEST_DELAY = 5
RETRY_DELAY = 60
MAX_RETRY = 5

success_symbols = 0
failed_symbols = []

for symbol in symbols:

    print(f"\n🔄 Processing: {symbol}")

    # ===== create stock object =====
    retry = 0
    while True:
        try:
            stock = vn.stock(symbol=symbol, source="VCI")
            break

        except ValueError:
            print(f"❌ Invalid symbol -> skip {symbol}")
            stock = None
            break

        except Exception as e:
            retry += 1
            print(f"⚠️ API error creating stock: {e}")

            if retry >= MAX_RETRY:
                print("⛔ Skip symbol")
                stock = None
                break

            print(f"⏳ retry in {RETRY_DELAY}s")
            time.sleep(RETRY_DELAY)

    if stock is None:
        failed_symbols.append(symbol)
        continue

    symbol_success = False   # đánh dấu nếu symbol có report thành công

    # ===== download reports =====
    for func, name in [
        (stock.finance.income_statement, "income_statement"),
        (stock.finance.balance_sheet, "balance_sheet"),
        (stock.finance.cash_flow, "cash_flow"),
    ]:

        retry = 0

        while True:
            try:

                print(f"   → {name}", end="")

                df = func(period="quarter")

                df["symbol"] = symbol
                df["report"] = name

                all_data.append(df)

                print(" ✅")

                symbol_success = True

                time.sleep(REQUEST_DELAY)
                break

            except Exception as e:

                retry += 1
                print(f"\n⚠️ error: {e}")

                if retry >= MAX_RETRY:
                    print("⛔ skip report")
                    break

                print(f"⏳ retry in {RETRY_DELAY}s")
                time.sleep(RETRY_DELAY)

    if symbol_success:
        success_symbols += 1
    else:
        failed_symbols.append(symbol)


final_df = pd.concat(all_data, ignore_index=True)

final_df.to_csv(
    "raw_financial_data.csv",
    index=False,
    encoding="utf-8-sig",
    float_format="%.0f"
)

print("\n🎉 DONE")
print("=================================")
print(f"Total symbols: {len(symbols)}")
print(f"Success symbols: {success_symbols}")
print(f"Failed symbols: {len(failed_symbols)}")
print("Failed list:", failed_symbols)

🔄 Processing: ACB
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: BCM

2026-03-11 15:52:54 - vnstock.core.utils.client - ERROR - API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

⚠️ API error creating stock: API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⏳ retry in 60s
   → income_statement ✅
   → balance_sheet

2026-03-11 15:55:28 - vnstock.core.utils.client - ERROR - API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2026-03-11 15:55:28 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu cân đối kế toán': API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2026-03-11 15:55:28 - vnstock.explorer.vci.financial - ERROR - Error retrieving balance sheet: API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2026-03-11 15:55:28 - vnstock.common.data - ERROR - Error fetching balance_sheet: API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

⚠️ error: API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⏳ retry in 60s
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: BID
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow

2026-03-11 15:59:34 - vnstock.core.utils.client - ERROR - API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2026-03-11 15:59:34 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2026-03-11 15:59:34 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu lưu chuyển tiền tệ': API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2026-03-11 15:59:34 - vnstock.common.data - ERROR - Error fetching cash_flow: API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

⚠️ error: API request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
⏳ retry in 60s

2026-03-11 16:00:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:00:34 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu lưu chuyển tiền tệ': API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:00:34 - vnstock.common.data - ERROR - Error fetching cash_flow: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

   → cash_flow
⚠️ error: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:01:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:01:34 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu lưu chuyển tiền tệ': API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:01:34 - vnstock.common.data - ERROR - Error fetching cash_flow: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

   → cash_flow
⚠️ error: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:02:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:02:34 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu lưu chuyển tiền tệ': API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:02:34 - vnstock.common.data - ERROR - Error fetching cash_flow: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

   → cash_flow
⚠️ error: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:03:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:03:34 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu lưu chuyển tiền tệ': API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:03:34 - vnstock.common.data - ERROR - Error fetching cash_flow: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:03:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

   → cash_flow
⚠️ error: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⛔ skip report

🔄 Processing: BVH
⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:04:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:05:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:06:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:07:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:07:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⛔ Skip symbol

🔄 Processing: CTG
⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:08:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:09:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:10:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:11:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:11:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⛔ Skip symbol

🔄 Processing: FPT
⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:12:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:13:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:14:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:15:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:15:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⛔ Skip symbol

🔄 Processing: GAS
⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:16:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:17:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:18:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:19:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:19:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⛔ Skip symbol

🔄 Processing: GVR
⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:20:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:21:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:22:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:23:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:23:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⛔ Skip symbol

🔄 Processing: HDB
⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:24:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:25:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:26:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:27:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:27:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⛔ Skip symbol

🔄 Processing: HPG
⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:28:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:29:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:30:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:31:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
2026-03-11 16:31:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⛔ Skip symbol

🔄 Processing: MBB
⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:32:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:33:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s

2026-03-11 16:34:34 - vnstock.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))

⚠️ API error creating stock: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Max retries exceeded with url: /data-mt/graphql (Caused by NameResolutionError("HTTPSConnection(host='trading.vietcap.com.vn', port=443): Failed to resolve 'trading.vietcap.com.vn' ([Errno 11001] getaddrinfo failed)"))
⏳ retry in 60s
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: MSN
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: MWG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PLX
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: POW
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: SAB
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: SSI
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: STB
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: TCB
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: TPB
⚠️ API error creating stock: Failed to fetch data: 502 - Bad Gateway
⏳ retry in 60s
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VCB
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VHM
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VIB
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VIC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VJC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VNM
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VPB
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VRE
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VND
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VIX
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DXG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DIG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: NLG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: KDH
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PDR
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: NVL
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: HDG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: CEO
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: SCR
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: HDC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: IDC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: BCG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: KBC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: SZC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: IJC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: TIP
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: NTL
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow

2026-03-11 16:49:19 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: Failed to fetch data: 502 - Bad Gateway
2026-03-11 16:49:19 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu lưu chuyển tiền tệ': Failed to fetch data: 502 - Bad Gateway
2026-03-11 16:49:19 - vnstock.common.data - ERROR - Error fetching cash_flow: Failed to fetch data: 502 - Bad Gateway

⚠️ error: Failed to fetch data: 502 - Bad Gateway
⏳ retry in 60s
   → cash_flow ✅

🔄 Processing: AGG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DRH
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: LDG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DGC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DCM
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DPM
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: CSV
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: LAS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: BFC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PLC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PGD
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PET
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PVT
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PVS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PVD
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: BSR
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: OIL
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: GEX
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: GEE
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PC1
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: TV2
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: REE
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: GEG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: NT2
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PPC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: HND
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: QTP
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: TTA
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VSH
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: SJD
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: TMP
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: CHP
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: CMG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DGW
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: FRT
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: CTR
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: ELC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VGI
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: FOX
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: SGT
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VTP
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: SCS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: PNJ
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DOJI
❌ Invalid symbol -> skip DOJI

🔄 Processing: FMC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: ANV
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: IDI
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VHC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: MPC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: ACL
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: LTG
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: DBC
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: HCM
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: VCI
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: BSI
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: SHS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: CTS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: FTS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: AGR
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: MBS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: BVS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🔄 Processing: TVS
   → income_statement ✅
   → balance_sheet ✅
   → cash_flow ✅

🎉 DONE
=================================
Total symbols: 109
Success symbols: 101
Failed symbols: 8
Failed list: ['BVH', 'CTG', 'FPT', 'GAS', 'GVR', 'HDB', 'HPG', 'DOJI']

In [4]:
final_df.columns

Index(['ticker', 'yearReport', 'lengthReport', 'Revenue (Bn. VND)',
       'Revenue YoY (%)', 'Attribute to parent company (Bn. VND)',
       'Attribute to parent company YoY (%)', 'Interest and Similar Income',
       'Interest and Similar Expenses', 'Net Interest Income',
       ...
       'Goodwill', 'Other current assets (Bn. VND)',
       'Profit/Loss from disposal of fixed assets',
       'Interest income and dividends', 'Finance lease principal payments',
       'Budget sources and other funds', 'Convertible bonds (Bn. VND)',
       '_Increase/Decrease in receivables', '_Increase/Decrease in payables',
       '_Other Reserves'],
      dtype='str', length=162)

In [5]:
final_df.head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Interest and Similar Income,Interest and Similar Expenses,Net Interest Income,...,Goodwill,Other current assets (Bn. VND),Profit/Loss from disposal of fixed assets,Interest income and dividends,Finance lease principal payments,Budget sources and other funds,Convertible bonds (Bn. VND),_Increase/Decrease in receivables,_Increase/Decrease in payables,_Other Reserves
0,ACB,2025,4,1.608042e+13,0.189523,2.784685e+12,-0.387357,1.608042e+13,-8.987152e+12,7.093272e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACB,2025,3,1.504940e+13,0.164628,4.280589e+12,0.105982,1.504940e+13,-8.279694e+12,6.769710e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACB,2025,2,1.429870e+13,0.146214,4.881159e+12,0.092326,1.429870e+13,-7.614847e+12,6.683848e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACB,2025,1,1.332731e+13,0.111758,3.678266e+12,-0.058164,1.332731e+13,-6.968441e+12,6.358865e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACB,2024,4,1.351838e+13,0.080173,4.545364e+12,0.134560,1.351838e+13,-6.438085e+12,7.080291e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print(final_df[final_df["ticker"]=="HPG"][["yearReport","lengthReport","Revenue (Bn. VND)"]])

Empty DataFrame
Columns: [yearReport, lengthReport, Revenue (Bn. VND)]
Index: []

In [7]:
df = final_df.dropna(axis=1, how="all")

In [8]:
df.head()

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Interest and Similar Income,Interest and Similar Expenses,Net Interest Income,...,Goodwill,Other current assets (Bn. VND),Profit/Loss from disposal of fixed assets,Interest income and dividends,Finance lease principal payments,Budget sources and other funds,Convertible bonds (Bn. VND),_Increase/Decrease in receivables,_Increase/Decrease in payables,_Other Reserves
0,ACB,2025,4,1.608042e+13,0.189523,2.784685e+12,-0.387357,1.608042e+13,-8.987152e+12,7.093272e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACB,2025,3,1.504940e+13,0.164628,4.280589e+12,0.105982,1.504940e+13,-8.279694e+12,6.769710e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACB,2025,2,1.429870e+13,0.146214,4.881159e+12,0.092326,1.429870e+13,-7.614847e+12,6.683848e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACB,2025,1,1.332731e+13,0.111758,3.678266e+12,-0.058164,1.332731e+13,-6.968441e+12,6.358865e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACB,2024,4,1.351838e+13,0.080173,4.545364e+12,0.134560,1.351838e+13,-6.438085e+12,7.080291e+12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN